version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=wheels
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    external: true
